In [1]:
import numpy as np

result = np.array([1,3,5,7,9])

print(result)

[1 3 5 7 9]


In [2]:
result = np.arange(1,10)
print(result)

[1 2 3 4 5 6 7 8 9]


In [3]:
result= np.arange(10,100,3)
result

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [5]:
result = np.zeros(10)
result

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
result = np.ones(10)
result

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
result = np.linspace(0,100,5)
result

array([  0.,  25.,  50.,  75., 100.])

In [10]:
result = np.random.randint(0,10)
result

9

In [11]:
result = np.random.randint(20)  # başlangıç sayısı 0 ise belirtmeye gerek yok
result

11

In [12]:
result = np.random.randint(0,10,3) # rastgele belirtilen aralıkta 3 tane sayı üret
result

array([7, 9, 4])

In [14]:
result = np.random.rand(5)
result

array([0.26325004, 0.57699089, 0.87618053, 0.89775724, 0.69159707])

In [15]:
result = np.random.randn(5)
result

array([ 0.73825359,  0.07128285,  1.13057833, -0.97056941,  0.09297995])

In [17]:
np_array = np.arange(50)
np_multi = np_array.reshape(5,10)
np_multi

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [20]:
print(np_multi.sum(axis=1))  # her bir satırın toplamı
print(np_multi.sum(axis=0))  # her bir sutunun toplamı

[ 45 145 245 345 445]
[100 105 110 115 120 125 130 135 140 145]


In [21]:
rnd_numbers = np.random.randint(1,100,10)
print(rnd_numbers)

[13 32 96 93 45 86 85 90 61 40]


In [22]:
rnd_numbers.max()

96

In [23]:
rnd_numbers.min()

13

In [24]:
rnd_numbers.mean()

64.1

In [25]:
rnd_numbers.argmax()  # üretilen max sayının index bilgisini verir

2

In [26]:
rnd_numbers.argmin()  # üretilen min sayının index bilgisini verir

0