In [1]:
import numpy as np

In [4]:
numbers = np.array([0,5,10,15,20,25,50,75])

In [5]:
numbers[5]

25

In [6]:
numbers[-1]

75

In [7]:
numbers[0:3]

array([ 0,  5, 10])

In [8]:
numbers[:3]

array([ 0,  5, 10])

In [9]:
numbers[3:]

array([15, 20, 25, 50, 75])

In [10]:
numbers[::]

array([ 0,  5, 10, 15, 20, 25, 50, 75])

In [11]:
numbers[::-1]

array([75, 50, 25, 20, 15, 10,  5,  0])

In [12]:
numbers[::-2]

array([75, 25, 15,  5])

In [13]:
numbers2 = np.array([[0,5,10], [15,20,25],[50,75,85]])

In [16]:
numbers2[0]

array([ 0,  5, 10])

In [15]:
numbers2[1]

array([15, 20, 25])

In [18]:
numbers2[0,2]

10

In [20]:
numbers2[:,1] # tüm satırlardaki 1. indexteki değerler

array([ 5, 20, 75])

In [21]:
numbers2[:]

array([[ 0,  5, 10],
       [15, 20, 25],
       [50, 75, 85]])

In [22]:
numbers2[-1,:]  # numbers2[2]

array([50, 75, 85])

In [27]:
arr1 = np.arange(0,10)
arr2 = arr1 # referans

In [29]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
arr2[0]= 20

In [31]:
arr2

array([20,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [32]:
arr1  # arr2 için yapılan değişiklikler arr1 i de etkiler

array([20,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [33]:
arr1 = np.arange(0,10)
arr2 = arr1.copy() # referans

In [34]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
arr2[0]= 20

In [37]:
arr2

array([20,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [39]:
arr1  # arr2 de yapılan değişiklik arr1 de geçerli olmadı

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])