In [1]:
import numpy as np

In [2]:
numbers1 = np.random.randint(10,100,6)
numbers2 = np.random.randint(10,100,6)

In [3]:
numbers1

array([86, 48, 25, 27, 38, 18])

In [4]:
numbers2

array([16, 33, 59, 54, 18, 78])

In [5]:
result = numbers1 + numbers2
result

array([102,  81,  84,  81,  56,  96])

In [7]:
numbers1 + 10   # her bir elemanı 1 ile toplanır

array([96, 58, 35, 37, 48, 28])

In [9]:
result = np.sin(numbers1)
result

array([-0.92345845, -0.76825466, -0.13235175,  0.95637593,  0.29636858,
       -0.75098725])

In [10]:
result = np.cos(numbers1)
result

array([-0.38369844, -0.64014434,  0.99120281, -0.29213881,  0.95507364,
        0.66031671])

In [11]:
mnumbers1 = numbers1.reshape(2,3)
mnumbers2 = numbers2.reshape(2,3)

In [12]:
mnumbers1

array([[86, 48, 25],
       [27, 38, 18]])

In [13]:
mnumbers2

array([[16, 33, 59],
       [54, 18, 78]])

In [17]:
result = np.vstack((mnumbers1,mnumbers2)) #dikey bir şekilde ekleme yaptı
result

array([[86, 48, 25],
       [27, 38, 18],
       [16, 33, 59],
       [54, 18, 78]])

In [18]:
result = np.hstack((mnumbers1,mnumbers2)) #yatay bir şekilde ekleme yaptı
result

array([[86, 48, 25, 16, 33, 59],
       [27, 38, 18, 54, 18, 78]])

In [20]:
result = numbers1 >= 30
result

array([ True,  True, False, False,  True, False])

In [21]:
result = numbers1 % 2 == 0
result

array([ True,  True, False, False,  True,  True])