In [1]:
import numpy as np

1 - (10,15,30,45,60) değerlerine sahip numpy dizisini oluşturunuz.

In [8]:
result = np.array([10,15,30,45,60])
result

array([10, 15, 30, 45, 60])

2- (5-15) arasındaki sayılarla numpy dizisini oluşturunuz.

In [12]:
result = np.arange(5,15)
result

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

3 - (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz

In [13]:
result = np.arange(50,100,5)
result

array([50, 55, 60, 65, 70, 75, 80, 85, 90, 95])

4 - 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.

In [15]:
result = np.zeros(10)
result

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

5 - 10 elemanlı birlerden oluşan bir dizi oluşturunuz.

In [16]:
result = np.ones(10)
result

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

6 - (0-100) arasında eşit aralıklı 5 sayı üretin.

In [19]:
result = np.linspace(0,100,5)
result

array([  0.,  25.,  50.,  75., 100.])

7- (10-30) arasındaki rastgele 5 tane tamsayı üretin.

In [23]:
result = np.random.randint(10,30,5)
result

array([11, 19, 28, 21, 27])

8- [-1 ile 1] arasına 10 adet sayı üretin

In [26]:
result =np.random.randn(10)
result

array([ 0.11984402, -1.15010525, -1.15216276, -0.14148797,  0.79689516,
       -0.88363091, -0.11637911, -2.40576468, -0.0426434 , -0.37885032])

9 - (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.

In [46]:
matris = np.random.randint(10,50,15)
matris = matris.reshape(3,5)
matris

array([[22, 12, 36, 47, 24],
       [15, 42, 44, 21, 11],
       [45, 42, 15, 36, 45]])

10 - üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?

In [47]:
satır = matris.sum(axis=1)
satır

array([141, 133, 183])

In [48]:
sutun = matris.sum(axis=0)
sutun

array([ 82,  96,  95, 104,  80])

11 - üretilen matrisin en büyük, en küçük ve ortalaması nedir ?

In [49]:
matris.max()

47

In [50]:
matris.min()

11

In [57]:
matris.mean()

30.466666666666665

12 - üretilen matrixin en büyük değerinin indeksi kaçtır?

In [58]:
result = matris.argmax()
result

3

13 - (10 - 20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.

In [53]:
arr = np.arange(10,20)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [54]:
arr[:3]

array([10, 11, 12])

14 - üretilen dizinin elemanlarını tersten yazdırınız

In [59]:
arr[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

15- üretilen matrisin ilk satırını seçiniz

In [60]:
matris[0]

array([22, 12, 36, 47, 24])

16 - üretilen matrisin 2.satır 3.sütundaki elemanı hangiisidir?

In [61]:
matris[1][2]

44

17- üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.

In [65]:
matris[:,0]

array([22, 15, 45])

18 - üretilen matrisin her bir elemanının karesini alınız

In [66]:
result = matris ** 2

In [67]:
result

array([[ 484,  144, 1296, 2209,  576],
       [ 225, 1764, 1936,  441,  121],
       [2025, 1764,  225, 1296, 2025]])